# Generated by Django 5.2.5 on 2025-09-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_buyerprofilemodel_sellerprofilemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('offer', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('color', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('others', models.JSONField(null=True)),
            ],
        ),
    ]
