# Generated by Django 5.2.5 on 2025-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
