# Generated by Django 5.2.5 on 2025-10-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_cartmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='review',
            field=models.JSONField(null=True),
        ),
    ]
