# Generated by Django 5.2.5 on 2025-10-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_productmodel_rating_productmodel_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='others',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='review',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.categorymodel'),
        ),
    ]
