# Generated by Django 5.2.5 on 2025-10-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_categorymodel_alter_productmodel_others_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='category',
            new_name='categoryName',
        ),
    ]
