# Generated by Django 5.2.5 on 2025-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_ordersmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodels',
            name='days',
            field=models.IntegerField(default=5),
        ),
    ]
