# Generated by Django 5.2.5 on 2025-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_ordersmodels_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
